# Generated by Django 4.0.1 on 2022-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('candidate_party', models.CharField(max_length=100)),
                ('candidate_pincode', models.IntegerField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
