# Generated by Django 4.0.1 on 2022-03-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_candidte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteModel',
        ),
        migrations.AddField(
            model_name='candidte',
            name='candidate_id',
            field=models.IntegerField(blank=True, default=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='candidate_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='if_face_verified',
            field=models.BooleanField(),
        ),
    ]
